name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --tag mich181189/emf2024jambonz:latest && docker tag mich181189/emf2024jambonz:latest mich181189/emf2024jambonz:${{env.GITHUB_RUN_NUMBER}}
    
